# Generated by Django 4.2.5 on 2023-12-19 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ai_response',
            name='userId',
        ),
        migrations.AddField(
            model_name='ai_response',
            name='doctor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ai_response_doctor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ai_response',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ai_response_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
