# Generated by Django 4.2.5 on 2023-10-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_response',
            name='description',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
