# Generated by Django 4.2.18 on 2025-01-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_galleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('restaurant_name', models.CharField(max_length=255)),
                ('story', models.TextField()),
                ('video_url', models.URLField()),
                ('delicious_title', models.CharField(max_length=255)),
                ('delicious_description', models.TextField()),
                ('romantic_title', models.CharField(max_length=255)),
                ('romantic_description', models.TextField()),
                ('chef_name', models.CharField(max_length=255)),
                ('chef_image', models.ImageField(upload_to='chefs/')),
                ('chef_description', models.TextField()),
            ],
        ),
    ]
