# Generated by Django 4.2.18 on 2025-01-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('story_title', models.CharField(max_length=255)),
                ('story_content', models.TextField()),
                ('video_title', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('bg_image', models.ImageField(upload_to='about_page/')),
            ],
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='chefs/')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
    ]
